Update training.md
spin-itn/spin-itn.github.io pull request #1
Opened 2021-01-25 14:22 UTC by Judape

added the training courses and workshops

2021-01-28 21:42 UTC, hadzii requested changes

2021-01-28 21:42 UTC, hadzii commented on docs/training.md
> +## Attendance and presentation at International Conference: General Assembly of the European Geoscience Union - EGU
Please remove the reference to conference presentations

2021-01-28 21:42 UTC, hadzii commented on docs/training.md
> +a 3D deployment). Goal: cross-validation of methodology and observations with different instrumentation.
'Goal' on newline and bold

2021-01-29 14:38 UTC, Judape commented on docs/training.md
> +a 3D deployment). Goal: cross-validation of methodology and observations with different instrumentation.
;)

2021-02-02 15:51 UTC, merged